### ISSUE TITLE
Electric Data no longer showing

### ISSUE THREAD

**Issue by owensy** [ianmccon/MMM-IntelligentOctopus#1]
Hi Mate

First off, great work on this module! I originally used the OctoMon this was forked from and the improvements you have made were exactly what i was waiting for.

This was working fine until a week or two ago when the electric data stopped showing. I dont know if this is just an issue for me, but i tested the api using soapui and it returns data no problem. I also added some extra logging in certain places to double check data is definitely being retrieved and it is but for some reason only my gas data is showing, even the elec heading isnt showing.

I'm on intelligent octopus tariff so i have fixedRateTarrif set to false. I tried setting it to true to see if it would display anything without having to do all the working out of peak/off peak costs, with true set it at least displays elec heading but all the values are empty.

The error in the browser console is:
Uncaught TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Class.processDailyConsumption (MMM-IntelligentOctopus.js:458:5)
    at Class.processElecData (MMM-IntelligentOctopus.js:420:29)
    at elecDataRequest.onreadystatechange (MMM-IntelligentOctopus.js:88:12)

Not sure if Octopus have changed something in the API, but I would love to get this working again!

**Comment by ianmccon** [comment]
I noticed that as well and assumed that something had changed in the API. I haven't had a chance to look into it before now but I may have time in the next day or two. I'll let you know

**Comment by owensy** [comment]
Great thanks! Just a thought but could it be the clocks changing for daylight savings? It looks like the API returns the times in summertime format rather than UTC

**Comment by ianmccon** [comment]
Yes, it was the clocks changing. I've fixed this and tidied up a few things as well. Please read the README as there are some changes needed to your config.js

**Comment by owensy** [comment]
Thanks Ian, its working again for me now, great to see!

Couple of things tho...
The readme says to use a config item called gas_mprn but the code is looking for gas_mpan
The readme has elec_serial twice, the second one should be called gas_serial

**Comment by ianmccon** [comment]
Good catch. I've corrected those typos.
